### ISSUE TITLE
KeyError error on embargoed dandisets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/backups2datalad#23]
We are getting failed runs with errors like

```
2024-02-05T11:02:55-0500 [ERROR   ] backups2datalad: Job failed on input <Dandiset 000361/draft>:                                                                                    
Traceback (most recent call last):                                                                                                                                                   
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/aioutil.py", line 176, in dowork                                                        
    outp = await func(inp)                                                                                                                                                           
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/datasetter.py", line 173, in update_dandiset                                            
    stats = await ds.get_stats(config=dmanager.config)                                                                                                                               
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/adataset.py", line 535, in get_stats                                                    
    for filestat in await self.get_file_stats():                                                                                                                                     
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/adataset.py", line 419, in get_file_stats                                               
    filedict[f.file] = replace(filedict[f.file], size=f.bytesize)                                                                                                                    
KeyError: 'sub-...SENSORED....nwb'   
```

on an embargoed dataset (thus I SENSORED the path just in case).  That https://github.com/dandisets/000361 is empty ... I reset hard and cleaned that and also a few other dandisets which were dirty -- didn't look into them

```
RuntimeError: Dirty Dandiset 000403/draft; clean or save before running
RuntimeError: Dirty Dandiset 000407/draft; clean or save before running
RuntimeError: Dirty Dandiset 000408/draft; clean or save before running
```

**Comment by yarikoptic** [comment]
dunno ... may be something racy happened?  after reset/clean/redo -- this one in particular is now seems populated so we need to close I guess until similar case happened again.
