### ISSUE TITLE
Populates local annex instead of dropbox, although marking "populated".

### ISSUE THREAD

**Issue by yarikoptic** [dandi/backups2datalad#37]
The idea is that we do not keep data locally but rather copy from web to dropbox.  But it seems that we are amassing data locally

```
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets$ du -scm */.git/annex/objects | grep -v '^0'
40      000025/.git/annex/objects
1383    000026/.git/annex/objects
1579    000035/.git/annex/objects
23502   000037/.git/annex/objects
41886   000039/.git/annex/objects
767     000043/.git/annex/objects
33395   000114/.git/annex/objects
8768    000121/.git/annex/objects
48      000122/.git/annex/objects
3088    000125/.git/annex/objects
1739    000127/.git/annex/objects
1152    000128/.git/annex/objects
49      000129/.git/annex/objects
27      000130/.git/annex/objects
2627    000148/.git/annex/objects
...
```

Taking a sample dandiset

```
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets$ ds=000674; ( cd $ds && du -scm .git/annex/objects; git annex find --in here --and --not  --in dandi-dandisets-dropbox; )
1469    .git/annex/objects
1469    total
sub-YinMPscMs1mm/ses-20230610h05m38s48/micr/sub-YinMPscMs1mm_ses-20230610h05m38s48_sample-ACEProteinSMI_SMI_stain-SMI.tiff
sub-YinMPscMs1mm/ses-20230611h01m56s56/micr/sub-YinMPscMs1mm_ses-20230611h01m56s56_sample-ACEProteinSox10_SOX10_stain-SOX10.tiff
sub-YinMPscMs1mm/ses-20230611h22m30s24/micr/sub-YinMPscMs1mm_ses-20230611h22m30s24_sample-ACEProteinAQP4_AQP4_stain-AQP4.tiff
```

so we have 3 files present locally but not in dropbox.  But we marked as it was `populated`

```shell
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets/000674$ git show | head -n 1
commit 1585e628468b5970e77e1f621f5c2ada15371934
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets/000674$ git config dandi.populated
1585e628468b5970e77e1f621f5c2ada15371934
```

<details>
<summary>some unfinished attempt to troubleshoot -- got to the point of having libssl issue</summary> 

if I unset that (`git config --unset dandi.populated`) and rerun cron script

```shell
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets/000674$ flock -E 0 -e -n /home/dandi/.run/backup2datalad-populate-cron.lock /mnt/backup/dandi/dandisets/tools/backups2datalad-populate-assets-cron 000674
> backups2datalad -l DEBUG --backup-root /mnt/backup/dandi --config tools/backups2datalad.cfg.yaml populate 000674
```

but that one hanged at that and in `ps auxw -H` it didn't show that `backups2datalad` process under that bash script hierarchy (found it later detached, so it is odd).  I interrupted 

but running directly until completion lead me to

```
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets$ backups2datalad -l DEBUG --backup-root /mnt/backup/dandi --config tools/backups2datalad.cfg.yaml populate 000674

2024-03-10T18:24:41-0400 [INFO    ] backups2datalad: Saving logs to /mnt/backup/dandi/dandisets/.git/dandi/backups2datalad/2024.03.10.22.23.49Z.log
2024-03-10T18:24:41-0400 [INFO    ] backups2datalad: COMMAND: /home/dandi/miniconda3/envs/dandisets-2/bin/backups2datalad -l DEBUG --backup-root /mnt/backup/dandi --config tools/backups2datalad.cfg.yaml populate 000674
2024-03-10T18:24:41-0400 [DEBUG   ] backups2datalad: Running: git -c receive.autogc=0 -c gc.auto=0 config --get dandi.populated [cwd=/mnt/backup/dandi/dandisets/000674]
2024-03-10T18:24:41-0400 [DEBUG   ] backups2datalad: Finished [rc=1]: git -c receive.autogc=0 -c gc.auto=0 config --get dandi.populated [cwd=/mnt/backup/dandi/dandisets/000674]
2024-03-10T18:24:41-0400 [DEBUG   ] backups2datalad: Running: git -c receive.autogc=0 -c gc.auto=0 show -s --format=%H [cwd=/mnt/backup/dandi/dandisets/000674]
2024-03-10T18:24:41-0400 [DEBUG   ] backups2datalad: Finished [rc=0]: git -c receive.autogc=0 -c gc.auto=0 show -s --format=%H [cwd=/mnt/backup/dandi/dandisets/000674]
2024-03-10T18:24:41-0400 [INFO    ] backups2datalad: Copying files for Dandiset 000674 to backup remote
2024-03-10T18:24:41-0400 [DEBUG   ] backups2datalad: Opening pipe to `git -c receive.autogc=0 -c gc.auto=0 annex copy -c annex.retry=3 --jobs 3 --fast --to dandi-dandisets-dropbox --exclude '.dandi/*' --json --json-error-messages` [cwd=/mnt/backup/dandi/dandisets/000674]
2024-03-10T18:25:19-0400 [DEBUG   ] backups2datalad: Command `git -c receive.autogc=0 -c gc.auto=0 annex copy -c annex.retry=3 --jobs 3 --fast --to dandi-dandisets-dropbox --exclude '.dandi/*' --json --json-error-messages` [cwd=/mnt/backup/dandi/dandisets/000674] exited with return code 0
2024-03-10T18:25:19-0400 [INFO    ] backups2datalad: git-annex copy -c annex.retry=3 --jobs 3 --fast --to dandi-dandisets-dropbox --exclude '.dandi/*': 3 files succeeded, 0 files failed
2024-03-10T18:25:19-0400 [DEBUG   ] backups2datalad: Opening pipe to `git -c receive.autogc=0 -c gc.auto=0 annex copy -c annex.retry=3 --jobs 3 --fast --from web --to dandi-dandisets-dropbox --exclude '.dandi/*' --json --json-error-messages` [cwd=/mnt/backup/dandi/dandisets/000674]
2024-03-10T18:25:24-0400 [DEBUG   ] backups2datalad: Command `git -c receive.autogc=0 -c gc.auto=0 annex copy -c annex.retry=3 --jobs 3 --fast --from web --to dandi-dandisets-dropbox --exclude '.dandi/*' --json --json-error-messages` [cwd=/mnt/backup/dandi/dandisets/000674] exited with return code 0
2024-03-10T18:25:24-0400 [INFO    ] backups2datalad: git-annex copy -c annex.retry=3 --jobs 3 --fast --from web --to dandi-dandisets-dropbox --exclude '.dandi/*': 22 files succeeded, 0 files failed
2024-03-10T18:25:24-0400 [DEBUG   ] backups2datalad: Running: git -c receive.autogc=0 -c gc.auto=0 push github git-annex [cwd=/mnt/backup/dandi/dandisets/000674]
2024-03-10T18:25:24-0400 [WARNING ] backups2datalad: Failed [rc=128]: git -c receive.autogc=0 -c gc.auto=0 push github git-annex [cwd=/mnt/backup/dandi/dandisets/000674]

Stdout: <empty>

Stderr:

    OpenSSL version mismatch. Built against 30000070, you have 30200010
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.

2024-03-10T18:25:24-0400 [ERROR   ] backups2datalad: Job failed on input PosixPath('/mnt/backup/dandi/dandisets/000674'):
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/aioutil.py", line 177, in dowork
    outp = await func(inp)
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/__main__.py", line 558, in populate
    await ds.call_git("push", "github", "git-annex")
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/adataset.py", line 219, in call_git
    await aruncmd(
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/aioutil.py", line 224, in aruncmd
    raise e
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/aioutil.py", line 206, in aruncmd
    r = await anyio.run_process(argstrs, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/anyio/_core/_subprocesses.py", line 85, in run_process
    raise CalledProcessError(cast(int, process.returncode), command, output, errors)
subprocess.CalledProcessError: Command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'push', 'github', 'git-annex']' returned non-zero exit status 128.
1 populate job failed
```

so it failed to push but it did succeed to copy some stuff

```
$ git-annex copy -c annex.retry=3 --jobs 3 --fast --from web --to dandi-dandisets-dropbox --exclude '.dandi/*': 22 files succeeded, 0 files failed
```

and here we have only 3 files

```shell
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets/000674$ git annex find --in here
sub-YinMPscMs1mm/ses-20230610h05m38s48/micr/sub-YinMPscMs1mm_ses-20230610h05m38s48_sample-ACEProteinSMI_SMI_stain-SMI.tiff
sub-YinMPscMs1mm/ses-20230611h01m56s56/micr/sub-YinMPscMs1mm_ses-20230611h01m56s56_sample-ACEProteinSox10_SOX10_stain-SOX10.tiff
sub-YinMPscMs1mm/ses-20230611h22m30s24/micr/sub-YinMPscMs1mm_ses-20230611h22m30s24_sample-ACEProteinAQP4_AQP4_stain-AQP4.tiff
```

and it is altogether 25 files on dropbox 

```
(dandisets-2) dandi@drogon:/mnt/backup/dandi/dandisets/000674$ git annex find --in dandi-dandisets-dropbox | wc -l
25
```

</details>

I think because we are having a generic `copy` , we might end up with some copies locally if were interrupted? or are then from previous run?

meanwhile I think we should 

- add ` --not --in dandi-dandisets-dropbox` to the `copy` command so we do not even go through the files if we know they are already there
- investigate and solve `ssh` issue

but mystery might not be solved with that alone.

I will run following in a loop across all to move & drop everything accumulated locally
```shell
(base) dandi@drogon:/mnt/backup/dandi/dandisets$ ds=000674; ( cd $ds && du -scm .git/annex/objects; git annex move -J 3 --to dandi-dandisets-dropbox --fast --in here --not --in dandi-dandisets-dropbox && git annex drop --all && datalad clean; du -scm .git/annex/objects; )
1469    .git/annex/objects
1469    total
drop SHA256E-s513106608--1af40ffeab3eaaadd0da46966a998ba916f13df2143cb0c5da4e8ad77099c80d.tiff ok
drop SHA256E-s513106608--c70bd8ee7b0bb18cf83662bf0ac27bd5a18f329b6d01f65968d951bb39859dad.tiff ok
drop SHA256E-s513106608--96c8c60dc23d42d63ab7859ae6fd02731b4e3499bdf83c1882164306bcdc1958.tiff ok
(recording state in git...)
clean(ok): .git/annex/tmp (directory) [Removed empty temporary annex directory]
clean(ok): .git/annex/transfer (directory) [Removed 3 annex temporary transfer directories: download, failed, upload]
0       .git/annex/objects
0       total
```

**Comment by jwodder** [comment]
@yarikoptic How were git and the OpenSSL library installed on the system?  Could you try updating/reinstalling both of them?

**Comment by jwodder** [comment]
@yarikoptic Running `conda update git` in the `dandisets-2` environment seemed to fix the problem.

**Comment by yarikoptic** [comment]
FTR, after I did some manual cleaning etc we have
```
dandi@drogon:/mnt/backup/dandi/dandisets$ du -scm */.git/annex/objects | grep -v '^0'
89737   000559/.git/annex/objects
89737   total
```
but the population script is running... will check tomorrow if anything changes (i.e. we got this down - so it was only temporary). if not - it would mean that might need further investigation

**Comment by yarikoptic** [comment]
ATM we have a good number of files not backed up.  I have ran

```
for d in 000*; do git -C $d annex find --not --in dandi-dandisets-dropbox | grep . && echo $d; done | tee /tmp/nobackedup.txt
```

and output is at http://www.oneukrainian.com/tmp/nobackedup.txt

**Comment by yarikoptic** [comment]
above is yet to be troubleshooted -- may be our `copy` or `move` is not sufficient somehow which lead to above situation that we update the mark of last population but then end up with assets not in backup.  Please troubleshoot @jwodder

**Comment by jwodder** [comment]
@yarikoptic Current observations:

* The `populate` cronjobs are currently disabled, with a comment stating that they're currently run "manually in screen."  However, based on the logs, it seems that the last time the `populate` command was run was April 12.

* I ran the below script to list all assets that are not currently in Dropbox and that were last modified before the time of the last `populate` command:

    ```shell
    #!/bin/bash
    set -ex
    cd /mnt/backup/dandi/dandisets

    CUTOFF=1712962995  # 2024-04-12T23:03:15Z

    for d in 00*
    do
        git -C "$d" annex find --not --in dandi-dandisets-dropbox \
        | while read -r fpath
        do
            changed="$(git -C "$d" log -1 --format=%cd --date=unix "$fpath")"
            if [ "$changed" -lt "$CUTOFF" ]
            then echo "$d $fpath $(date -u --date=@"$changed" +%FT%TZ)" | tee -a ~/undropped-added.txt
            fi
        done
    done
    ```

    This returned 27905 assets in 111 Dandisets.  However, all of the Dandisets either are currently embargoed or (in the case of 000408) were only unembargoed after the latest `populate` run.

* The logs for the latest `populate` run list a number of failed `git annex copy` commands, all with the error message "no known url".  All the ones I've checked have been for embargoed Dandisets, and the assets that failed to copy do have `web` URLs registered.  I think the failure is because `backups2datalad` isn't passing `DATALAD_dandi_token` to `git-annex copy`.  For the record, do we want to copy embargoed assets to Dropbox or not?

**Comment by yarikoptic** [comment]
Thanks for the investigation.  I could have sworn that I did rerun population a few times since then but "logs do not lie", so might have been that bad.

`dropbox` is soon to go away, that is why I populating (fetching from S3) released versions of dandisets.  I guess we could still run population job to feed them to dropbox as well for nowbeing but I think that ample dropbox will seeze to become available within a month or so.

>  I think the failure is because backups2datalad isn't passing DATALAD_dandi_token to git-annex copy. For the record, do we want to copy embargoed assets to Dropbox or not?

I vaguely remember doing something about authentication recently but I think it was about github ... forgot.  Since dropbox is soon no more, let's not bother populating for embargoed, but we need to make sure that we are adding urls for embargoed assets correctly, IIRC they are to be handled via `datalad` special remote from API URLs.   Hence we have that

- https://github.com/dandi/backups2datalad/issues/35

**Comment by jwodder** [comment]
@yarikoptic I've updated the code to not populate embargoed Dandisets (#47), and #35/#36 is blocked by a need for newer git-annex.  Is there anything more to be done for this issue specifically?

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
I think there is a remaining issue here but as I am actually now fetching content for released dandisets to drogon, it becomes kinda difficult to test/troubleshoot, so let's indeed close for now.
