### ISSUE TITLE
--mode verify detects lots of unexpected diffs in metadata without server timestamp boost

### ISSUE THREAD

**Issue by yarikoptic** [dandi/backups2datalad#49]
After 
- #48 

I manually ran the `--mode verify` sweep and it errorred out quite loudly -- here is the trail pointing to the full log

```
    +---------------- 15 ----------------
    | Traceback (most recent call last):
    |   File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/asyncer.py", line 257, in process_blob
    |     raise UnexpectedChangeError(
    | backups2datalad.util.UnexpectedChangeError: Dandiset 000966: Metadata for asset sub-M230804-1/sub-M230804-1_ses-20231229T155815_ecephys.nwb was changed/added but draft timestamp was not updated on server:
    |
    | Metadata diff:
    |
    | --- old-metadata
    | +++ new-metadata
    | @@ -13,7 +13,7 @@
    |    contentSize: 247230064
    |    contentUrl:
    |    - https://api.dandiarchive.org/api/assets/acf6172c-d85f-4a22-ae19-6ba011a53e31/download/
    | -  - https://dandiarchive-embargo.s3.amazonaws.com/000966/blobs/b53/94e/b5394ed4-e80f-4fdf-bbc8-5d82717cf42a
    | +  - https://dandiarchive.s3.amazonaws.com/blobs/b53/94e/b5394ed4-e80f-4fdf-bbc8-5d82717cf42a
    |    dateModified: '2024-04-21T18:07:38.991543-04:00'
    |    digest:
    |      dandi:dandi-etag: 8fa0a66dc8ae41e2f124bf036cfc6594-4
    | @@ -77,6 +77,6 @@
    |        schemaKey: Software
    |        url: https://github.com/dandi/dandi-cli
    |        version: 0.61.2
    | -modified: '2024-04-21T22:07:46.774560Z'
    | +modified: '2024-04-29T19:35:16.321230Z'
    |  path: sub-M230804-1/sub-M230804-1_ses-20231229T155815_ecephys.nwb
    |  size: 247230064
    |
    |
    +---------------- ... ----------------
    | and 3 more exceptions
    +------------------------------------
2024-06-06T20:28:53-0400 [ERROR   ] backups2datalad: An error occurred:
Traceback (most recent call last):
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/__main__.py", line 119, in wrapped
    await f(datasetter, *args, **kwargs)
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/__main__.py", line 228, in update_from_backup
    await datasetter.update_from_backup(dandisets, exclude=exclude)
  File "/home/dandi/miniconda3/envs/dandisets-2/lib/python3.10/site-packages/backups2datalad/datasetter.py", line 94, in update_from_backup
    raise RuntimeError(
RuntimeError: Backups for 162 Dandisets failed
Logs saved to /mnt/backup/dandi/dandisets/.git/dandi/backups2datalad/2024.06.07.00.22.30Z.log
action summary:
  publish (notneeded: 2)
```

from which it looks like potentially unemabrgoing forgetting to reset the `modified` may be?

**Comment by jwodder** [comment]
@yarikoptic The error message seems pretty clear to me:

> backups2datalad.util.UnexpectedChangeError: Dandiset 000966: Metadata for asset sub-M230804-1/sub-M230804-1_ses-20231229T155815_ecephys.nwb was changed/added but draft timestamp was not updated on server

This is the Archive's fault for not updating the Dandiset's draft version's `modified` timestamp upon unembargoing.  Running the backup command with `--mode force` should get rid of the error.

**Comment by yarikoptic** [comment]
But it is `RuntimeError: Backups for 162 Dandisets failed` -- is there already so many dandisets which were unembargoed??? (very unlikely)

**Comment by jwodder** [comment]
@yarikoptic Based on the below script, there are only 6 Dandisets that have been unembargoed (000253, 000408, 000773, 000774, 000897, and 000935).

Is the problem described in the original comment still an issue?

```bash
#!/bin/bash
set -eu -o pipefail

dandiset_root=/mnt/backup/dandi/dandisets

cd "$dandiset_root"
for ds in 0*
do
    embargo_status="$(git -C "$ds" config --file .datalad/config --default OPEN --get dandi.dandiset.embargo-status)"
    if [ "$embargo_status" = OPEN ] \
        && git -C "$ds" log -S EMBARGOED -n1 -- .datalad/config | grep -q .
    then echo "$ds"
    fi
done
```

**Comment by jwodder** [comment]
@yarikoptic Ping.

**Comment by yarikoptic** [comment]
blocked by #56 ATM. Please just rerun that command with --verify whenever we do not have ongoing backup process running

**Comment by jwodder** [comment]
@yarikoptic This problem is still occurring, but seeing as it's affecting Dandisets that are still embargoed, the problem seems to be solely with Dandi Archive.  I have filed https://github.com/dandi/dandi-archive/issues/2002.

**Comment by yarikoptic** [comment]
<details><summary>on 000719  zarr issue getting the bits together </summary>

```
{
  "identifier": "000719",
  "created": "2023-11-30T17:09:30.037534Z",
  "modified": "2024-08-22T18:28:38.706169Z",
```
- zarr is in `"status": "Pending",`
- that path was added (or is that mtime from filesystem???) on 2024-04-02 13:03
```shell
dandi@drogon:~$ s3cmd -c ~/.s3cfg-dandi-backup ls -l s3://dandiarchive/zarr/7e1b3b36-a94a-427f-9793-b14e344a04f2/acquisition/TwoPhotonSeries/data/10006.5.7
2024-04-02 13:03        24908  5feda0eb2702d2422f1451d873caf677     STANDARD     s3://dandiarchive/zarr/7e1b3b36-a94a-427f-9793-b14e344a04f2/acquisition/TwoPhotonSeries/data/10006.5.7
```

our local zarr git has clean state and

```
dandi@drogon:/mnt/backup/dandi/dandizarrs/7e1b3b36-a94a-427f-9793-b14e344a04f2$ git show | head -n 20
commit e0f66f4592
Author: DANDI User <info@dandiarchive.org>
Date:   2024 Apr 19 13:25:56 -0400

    [backups2datalad] 510 files added, checksum updated

diff --git a/.dandi/s3sync.json b/.dandi/s3sync.json
index 7a9cc99208..fee70574e1 100644
--- a/.dandi/s3sync.json
+++ b/.dandi/s3sync.json
@@ -1,5 +1,5 @@
 {
     "bucket": "dandiarchive",
     "prefix": "zarr/7e1b3b36-a94a-427f-9793-b14e344a04f2/",
-    "last_modified": "2024-04-02T17:07:01Z"
+    "last_modified": "2024-04-19T17:25:56Z"
 }
```
and no file `acquisition/TwoPhotonSeries/data/10006.5.7` , and git on dandiset itself has commit in Oct

```
dandi@drogon:/mnt/backup/dandi/dandisets/000719$ git status
On branch draft
Your branch is up to date with 'github/draft'.

nothing to commit, working tree clean
dandi@drogon:/mnt/backup/dandi/dandisets/000719$ git show | head 
commit 4a67e06
Author: DANDI User <info@dandiarchive.org>
Date:   2024 Oct 02 22:12:48 -0400

    [backups2datalad] 1 file added
```

I wish we had audit readily available to get records on this zarr to check exactly what/when was happening on that zarr ...

</details>

**Comment by jjnesbitt** [comment]
@yarikoptic What is the concise bug report that we could move forward on solving in the archive once we're able? Is it mainly that the metadata of dandiset draft versions are updated _without_ the `modified`field  being updated as well?

**Comment by yarikoptic** [comment]
for non-zarr assets -- I have not troubleshooted to the form beyond the fact that changes to **assets** (not dandiset level) metadata **did not result** in the change of the dandiset `modified` field. It might as well be the same issue as just filed 
- https://github.com/dandi/dandi-archive/issues/2050

may be you reextracted some metadata for some assets (listed in above report) also modifying them inplace and thus not triggering `modified` time stamp for the **dandiset** to change?

for zarr -- filed
- https://github.com/dandi/dandi-archive/issues/2051

**Comment by yarikoptic** [comment]
Update: fresh sweep brought up many "new" cases of changes where e.g. assets went from being Public to Embargoed (or the other way) due to I guess some internal metadata record fixups etc.  Some kind of summary with the pointer to the log to potentially retrospect

```
dandi@drogon:/mnt/backup/dandi/dandisets$ grep 'util\.Unexpected' /mnt/backup/dandi/dandisets/.git/dandi/backups2datalad/2025.02.04.16.18.17Z.log | sed -E 's,0[0-9]{5},DANDISETID,g' | sed -e 's,for asset [^ ]*,for asset PATH,g' | sort | uniq -c
      1     | backups2datalad.util.UnexpectedChangeError: Dandiset DANDISETID: Metadata for asset PATH (2)/sub-Temp-pref-F28-B28-6dpf-01-unsorted-nac (2)_ses-2DANDISETID3T112200_behavior.nwb was changed/added but draft timestamp was not updated on server:
      1     | backups2datalad.util.UnexpectedChangeError: Dandiset DANDISETID: Metadata for asset PATH (2)/sub-Temp-pref-F28-B28-6dpf-02-unsorted-nac (2)_ses-2DANDISETID3T115300_behavior.nwb was changed/added but draft timestamp was not updated on server:
   1398     | backups2datalad.util.UnexpectedChangeError: Dandiset DANDISETID: Metadata for asset PATH was changed/added but draft timestamp was not updated on server:
      1     | backups2datalad.util.UnexpectedChangeError: Dandiset DANDISETID: Zarr 1c0e023e-150d-43a7-948b-dc46dd514ca6: entry '.zattrs' added, but Dandiset draft timestamp was not updated on server
```

To get cleaner/smaller picture I am rerunning it now with `--mode force` and then would redo with `--mode verify` and hopefully regain some stable state again to work from

**Comment by yarikoptic** [comment]
this is way too old... I have reran with verify and we got only a few I will file in a new report
